Apply Remove overridden assignment JDT clean in core.resources
eclipse-platform/eclipse.platform.resources pull request #127
Opened 2022-05-11 15:32 UTC by vogella

Dogfooding the improve JDT cleanup from Bug 572440 to ensure the JDT
cleanup is stable and functional. Push in small chunks to make review
easier.

2022-05-11 16:19 UTC, iloveeclipse requested changes

2022-05-11 16:19 UTC, iloveeclipse commented on bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/utils/FileUtil.java
> -		// if the file does not exist or has no content yet, try with project preferences
Please restore comment

2022-05-12 05:24 UTC, vogella commented on bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/utils/FileUtil.java
> -		// if the file does not exist or has no content yet, try with project preferences
Done

2022-05-12 06:14 UTC, akurtakov approved these changes

2022-05-12 06:18 UTC, merged